[project]
name = 'parake_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.memory_with_expiry]
path = 'contracts/memory_with_expiry.clar'
clarity_version = 2
epoch = 2.5

[contracts.research]
path = 'contracts/research.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
